### ISSUE TITLE
saving the vectorDB

### ISSUE THREAD

**Issue by theohsiung** [melodylife/multimodalRAG#1]
感謝分享這棒的work，但我該如何更換summary的model為local端的llava模型，因為api等待時間過久。
另外想請問我不想要每次都重新生成vectorDB那部份，有些檔案事故定會用到的，我希望能將embedding後的資料存在local的file每一次運行都載入以節省embedding的時間

**Comment by melodylife** [comment]
抱歉這麼久才回覆。
Q1，在slider menu最上方，是summary model的選擇的radio button，選擇ollama之後，下面的模型裡面就會出現響應的local模型選擇。
Q2，可以的，不過你需要把vectorDB存儲到本地，然後在load的時候從local load，這部分代碼很抱歉我沒有demo，如果你需要我晚點可以更新。
感謝關注😁

**Comment by melodylife** [comment]
> 感謝分享這棒的work，但我該如何更換summary的model為local端的llava模型，因為api等待時間過久。 另外想請問我不想要每次都重新生成vectorDB那部份，有些檔案事故定會用到的，我希望能將embedding後的資料存在local的file每一次運行都載入以節省embedding的時間

抱歉这么久才回复，
Q1，可以的，在slider menu最上方，選擇ollama。如果你需要使用llava模型，首先在配置的config裡面添加llava作為選項，然後使用ollama pull預載一下這個model，就可以使用了。 
Q2，可以的。抱歉我沒有在程式裡面的實現。如果需要這樣做我建議如下修改。
1. 把檔案的ingestion過程獨立一個腳本。然後存放為本地的vectorDB檔案
2. 在retriever裡面修改載入，載入本地的vectore數據即可。
我後面找到時間，盡量更新這部分。
感謝關注 ：D

**Comment by theohsiung** [comment]
謝謝你! 以上的問題我都已經解決了
